sudo: required
services:
  - docker

before_install:
  - docker build -t chetanpatil112/docker-react -f Dockerfile.dev .

script:
  - docker run chetanpatil112/docker-react npm run test -- --coverage
