sudo: required
services:
  - docker

before_install:
  - sudo gem install bundler
  - docker build -t chetanpatil112/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chetanpatil112/docker-react npm run test
