sudo: required
services:
  - docker

before_install:
  - sudo gem install bundler
  - docker build -t chetanpatil112/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chetanpatil112/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-React"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-804602919378"
  bucket_path: "Docker-React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
